[app]
title = 排班闹钟
package.name = shiftalarm
package.domain = org.shiftalarm
source.dir = .
source.include_exts = py,png,jpg,kv,atlas,ttf
version = 0.1
version.code = 1
requirements = python3,kivy==2.3.1,plyer
android.permissions = VIBRATE,WAKE_LOCK,RECEIVE_BOOT_COMPLETED,POST_NOTIFICATIONS
icon.filename = icon.png
orientation = portrait
fullscreen = 0
android.minapi = 21
android.api = 34
android.ndk = 27c
android.sdk = 34
android.enable_androidx = True
android.java.source = 17
log_level = 2
warn_on_root = 0
